version: '3'
services:
 mysql:
  container_name: mysql57seb
  image: mysql:5.7
  environment:
   MYSQL_DATABASE: 'user_access'
   MYSQL_USER: 'springuser'
   MYSQL_PASSWORD: 'ThePassword'
   MYSQL_ROOT_PASSWORD: 'mypassword'
#   MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  ports:
   - '3306:3306'
  volumes:
   - mysql-demo1:/var/lib/mysql
  network_mode: 'host'
volumes:
  mysql-demo1:
