version: '3'
services:
  mysql:
    container_name: mysql57seb
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'user_access'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'ThePassword'
      MYSQL_ROOT_PASSWORD: 'mypassword'
    ports:
      - '3306:3306'
    volumes:
      - mysql-demo1:/var/lib/mysql
    network_mode: 'host'
  backed-app:
    container_name: backend-demo-seb
    image: backend-demo
    environment:
      MYSQL_DATABASE: 'user_access'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'ThePassword'
    ports:
      - '8080:8080'
    network_mode: 'host'
volumes:
  mysql-demo1:
